### PR TITLE
chore: changing codeowners of anypointmq binding

### PR DESCRIPTION
**Pull request by GeraldLoeffler**
**Description**

@GeraldLoeffler has resigned from Salesforce and therefore wants to transition ownership of the binding for Anypoint MQ (a Salesforce/MuleSoft product) to volunteers who are still Salesforce employees. Mihael Bosnjak (@mihaelmulesoft) and Jose Estefania Aulet (@jestefaniaaulet) have kindly come forward forward to co-own this binding.

Changing `CODEOWNERS` file accordingly.

### CODE REVIEW

**Comment by M3lkior** [comment]
Hi @GeraldLoeffler; i think that @mihaelmulesoft and @jestefaniaaulet should meet the AsyncAPI community and works one some first PRs before becoming maintainer of this repository, no ?

**Comment by char0n** [comment]
@derberg @fmvilas what's the policy and guidance in this situations? Is the code-ownership something that can assigned/inherited (given that there are volunteers)? IMHO this needs your input.

**Comment by GeraldLoeffler** [comment]
no @derberg , there is no obvious outstanding work to be done on the current binding. But maybe @mihaelmulesoft and @jestefaniaaulet will will have some ideas once they look into it in detail.

also, to ease the transition away from me, I can offer to mentor their work on the first 1 or 2 PRs that they will work on - whenever that is.

**Comment by derberg** [comment]
Would be good if @mihaelmulesoft and @jestefaniaaulet could join this PR and introduce

**Comment by derberg** [comment]
@GeraldLoeffler can you check with @mihaelmulesoft and @jestefaniaaulet. Maybe they need a call and some onboarding. I'm happy to help.

**Comment by mihaelmulesoft** [comment]
@derberg We already had a nice onboarding session with Gerald. Happy and ready to support working on the anypointmq bidnings

**Comment by derberg** [comment]
@GeraldLoeffler @mboss37 since @jestefaniaaulet is not active here, nor in the https://github.com/asyncapi/bindings/pull/203 I suggest he is not yet added to codeowners. We need people that are responsive that we can rely on.

**Pull request merged**
