### PR TITLE
fix: remove git HEAD marks left in Kafka binding README.md

### PR DESCRIPTION
**Pull request by smoya**
**Description**

This PR fixes a wrong git merge that happened in [kafka/README.md](kafka/README.md) file in https://github.com/asyncapi/bindings/pull/143#issuecomment-1798054517

**Related issue(s)**
https://github.com/asyncapi/bindings/pull/143#issuecomment-1798054517

cc @char0n

### CODE REVIEW

**Review by char0n — APPROVED** [review]

**Comment by char0n** [comment]
@lbroudoux @dalelane would you please look into this? It's a simple editorial change fixing remnants of the merge

**Comment by lbroudoux** [comment]
Thanks for the heads-up. We agreed with @dalelane in the previous [#182 comment](https://github.com/asyncapi/bindings/issues/182#issuecomment-1792837812) to fix this one when updating bindings for v3. Thus, the fix is integrated within #221 

I think we can cancel this one as changes in #221 are larger.

**Comment by smoya** [comment]
@lbroudoux I believe we should merge this asap. https://github.com/asyncapi/bindings/pull/221 is still under discussion regarding branch strategy, etc.
This PR though is fixing current `master`, which is currently showing ambiguity in the Message binding 
Google Chrome_iicWh2oL

**Comment by lbroudoux** [comment]
Going to review and merge it following the hold on discussions on #221 in https://github.com/asyncapi/bindings/issues/182#issuecomment-1825860815.

**Review by lbroudoux — APPROVED** [review]
LGTM!

**Pull request merged**
