### PR TITLE
fix: removed all json-schemas file

### LINKED ISSUE #183: Remove all JSON Schema files after spec 3.0 release
#### Reason/Context
After spec 3.0 release all schema files will be located in the spec-json-schema repository, where all codeowners for the bindings will also become codeowners for their respectful bindings. 

https://github.com/asyncapi/spec-json-schemas/tree/next-major-spec/bindings

Therefore we need to remove the schema files from this repository.

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**
This PR removed all the json-schemas file of the repository

**Related issue(s)**

Resolves #183

### CODE REVIEW

**Review by KhudaDad414 — APPROVED** [review]
Waiting for 3.0 Release :)

**Comment by sambhavgupta0705** [comment]
Still relevant,waiting for spec 3.0 release:)

**Comment by jonaslagoni** [comment]
@sambhavgupta0705 you can go ahead and re-target the PR to `next-major-spec` and then we can get this PR merged ASAP 🙂

**Comment by sambhavgupta0705** [comment]
@jonaslagoni re targeted the PR

**Comment by sambhavgupta0705** [comment]
@jonaslagoni I have updated it now.PTAL

**Review by fmvilas — APPROVED** [review]
@sambhavgupta0705 aka "el destructor" 🔥

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
@jonaslagoni ready to merge, but leaving it up to you when to do it as not sure if you want https://github.com/asyncapi/bindings/issues/183 closed now or later

**Comment by jonaslagoni** [comment]
@derberg @fmvilas might need a manual merge 🤔

**Comment by smoya** [comment]
This actually made me laugh 😆 

> @sambhavgupta0705 aka "el destructor" 🔥

gozer

**Pull request merged**
