### PR TITLE
fix(ibmmq): make topic field optional

### PR DESCRIPTION
**Pull request by char0n**
When `destinationType=topic`, `queue` field MUST NOT be present and topic MAY be defined.

Refs #169

---

This change is a reaction to https://github.com/asyncapi/bindings/pull/169#issuecomment-1357795258 and https://github.com/asyncapi/bindings/pull/169#issuecomment-1359075613

### CODE REVIEW

**Comment by char0n** [comment]
@rcoppen please have a look at this as well.

**Review by rcoppen — APPROVED** [review]

**Comment by derberg** [comment]
@KhudaDad414 as it involves json schemas, you need to approve too

@jonaslagoni yo, pinging you so you know to update https://github.com/asyncapi/spec-json-schemas/pull/239

**Comment by derberg** [comment]
@KhudaDad414 and yeah, when you approve, please merge

**Review by KhudaDad414 — APPROVED** [review]

**Comment by KhudaDad414** [comment]
@jonaslagoni should we revert it and merge it with the version change? 🤔

**Comment by derberg** [comment]
@KhudaDad414 @jonaslagoni but this was change in the schema only. The binding spec is correct and says `optional`, just the schema mistakenly `required` it. So it is bug in schema, not really a change in a spec. So IMHO no version bump

**Comment by jonaslagoni** [comment]
Ahh, okay 👍

**Comment by jonaslagoni** [comment]
I will update the schema once https://github.com/asyncapi/spec-json-schemas/pull/239 is merged.

**Pull request merged**
