### PR TITLE
feat: enable extensions in bindings

### PR DESCRIPTION
**Pull request by derberg**
Related https://github.com/asyncapi/spec/pull/893

This PR once and for all makes it clear that bindings are also extendable like other parts of AsyncAPI spec with specification extensions (`x-whatever`)

- this PR updates all bindings with info about specification extension
- this PR bumps versions of bindings and update their schemas

---

## One open questions, something maybe controversial

In this PR I also suggest that text:
```
This object MUST NOT contain any properties. Its name is reserved for future use.
```

is replaced everywhere with:
```
This object does not contain any fixed fields. Its name is reserved for future use.

This object MAY be extended with [Specification Extensions](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#specification-extensions).
```

The fact that we do not have any fixed fields for some binding should not block users from experimenting with extensions. So above change is needed if we want to truly enable extensions in all the bindings.
This change is visible in [this commit](https://github.com/derberg/bindings/commit/5d19c73b921d53b3cee1325ea01280d4051ae695). I did not provide schemas for these bindings yet, as first I want to be sure it is widely accepted.

### CODE REVIEW

**Review by VisualBean — COMMENTED** [review]
Why are the versions changing for the Json schemas, but nothing actually changed in them?
I believe most, if not all, already had the extension regex.

**Comment by derberg** [comment]
@VisualBean yes, you are right, we had extensions enabled on JSON Schema level. But readme text was saying something different. JSON Schema is considered to be a "tool" helpful for validation and other stuff. Individual binding readme is what is the "truth", so if we make some changes there that change behaviour, we need to bump the version of the binding. And yeah, texts in readmes were saying that basically "no props" should be added (which also includes extension).

Does that make sense?

**Comment by VisualBean** [comment]
> @VisualBean yes, you are right, we had extensions enabled on JSON Schema level. But readme text was saying something different. JSON Schema is considered to be a "tool" helpful for validation and other stuff. Individual binding readme is what is the "truth", so if we make some changes there that change behaviour, we need to bump the version of the binding. And yeah, texts in readmes were saying that basically "no props" should be added (which also includes extension).
> 
> Does that make sense?

I'm surprised that the "text" side of the documentation is what is considered the "truth" - with that in mind, the change makes sense.

**Review by VisualBean — APPROVED** [review]

**Comment by derberg** [comment]
@VisualBean yes, mainly because not all the things can be described with JSON Schema.

It is the same with main spec. 
- this is source of truth https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md
- this is just a helper tool https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/2.5.0.json

this is why also binding's JSON Schema files will be also moved to `spec-json-schemas` repo -> https://github.com/asyncapi/bindings/issues/113

---

Thanks so much for the approval and quick reaction 🙇

**Comment by VisualBean** [comment]
> @VisualBean yes, mainly because not all the things can be described with JSON Schema.
> 
> It is the same with main spec. 
> - this is source of truth https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md
> - this is just a helper tool https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/2.5.0.json
> 
> this is why also binding's JSON Schema files will be also moved to `spec-json-schemas` repo -> https://github.com/asyncapi/bindings/issues/113
> 
> ---
> 
> Thanks so much for the approval and quick reaction 🙇 

Any time. I think my reason for thinking it was the schema that was the truth, is that it is machine verifiable, so to speak, where the "text" isn't. 

Anyway, you are very welcome.

**Review by KhudaDad414 — APPROVED** [review]
LGTM!

**Review by CameronRushton — APPROVED** [review]
Solace stuff looks good to me. Thanks!

**Review by GeraldLoeffler — APPROVED** [review]
reviewed and approved anypointmq binding

**Review by dalelane — APPROVED** [review]
makes sense to me 👍

**Review by rcoppen — APPROVED** [review]

**Review by char0n — APPROVED** [review]
> The fact that we do not have any fixed fields for some binding should not block users from experimenting with extensions. So above change is needed if we want to truly enable extensions in all the bindings.

Amen ;]


LGTM and nice work! :tada: 

The sentence `This object MAY be extended with [Specification Extensions](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#specification-extensions)` is always in right place, right under the list of fixed fields (if they exists).

**Comment by derberg** [comment]
only few of you left to accept 😄 

@whitlockjc @fmvilas @smoya @lbroudoux @damaru-inc

**Review by whitlockjc — APPROVED** [review]
👍 for `googlepubsub`.

**Review by damaru-inc — APPROVED** [review]

**Comment by derberg** [comment]
@lbroudoux @fmvilas @smoya need your approval folks

**Review by smoya — APPROVED** [review]
LGTM! 🚀🌔

**Comment by lbroudoux** [comment]
Looks good to me 👍

**Review by lbroudoux — APPROVED** [review]
Kafka part looks good 🚀

**Comment by fmvilas** [comment]
@derberg I think we can merge this now, right?

**Pull request closed without merging**
