### PR TITLE
docs: update solace README.md

### PR DESCRIPTION
**Pull request by mhaque07**
docs: update solace README.md

**Description**

- style: Changes that do not affect the meaning of the code ( tabular views were broken under the Readme file)
- docs: Documentation only changes

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@mhaque07 Please update PR's title to the `docs: update solace README.md`

**Review by damaru-inc — APPROVED** [review]

**Review by VisualBean — APPROVED** [review]

**Comment by derberg** [comment]
@mhaque07 sorry, not sure why it was not merged at the approval time. There are some conflicts, can you 🙏🏼 address them?

**Comment by jonaslagoni** [comment]
ping ping @mhaque07

**Comment by smoya** [comment]
@mhaque07 please reopen this PR if it still applies. 

Thanks!

**Pull request closed without merging**
