### PR TITLE
feat: solace bindings new properties

### PR DESCRIPTION
**Pull request by DharinaHanumunthadu**
**Description**

- Adding two new fields to the solace binding, `maxMsgSpoolUsage` and `maxTtl`
- Fixing a typo in the existing field name for `msgVpn` in the `server.json` file
- Updating and fixing the readme formatting
Screen Shot 2022-10-26 at 2 18 53 PM

**Related issue(s)**
 
https://github.com/asyncapi/bindings/issues/147

### CODE REVIEW

**Comment by CameronRushton** [comment]
Binding version number should be incremented. Otherwise, LGTM.

**Review by damaru-inc — DISMISSED** [review]

**Review by CameronRushton — APPROVED** [review]
I think this is good, though I'm not very confident in my ability to review in this repo. I'd feel better if @damaru-inc took another look as well.
Thanks Dharina!

**Review by damaru-inc — APPROVED** [review]

**Comment by jessemenning** [comment]
looks good to me

**Review by KhudaDad414 — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
