### PR TITLE
feat!: release v3 compatible bindings

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR releases all the changes we did in the `next-major-spec` branch that has all the v3 compatible bindings.

### CODE REVIEW

**Review by derberg — APPROVED** [review]

**Comment by smoya** [comment]
When merging, please add the following commit message description literally (with the two empty lines at the beginning as well):

```


Co-authored-by: Sergio Moya <1083296+smoya@users.noreply.github.com>
Co-authored-by: Sambhav Gupta <81870866+sambhavgupta0705@users.noreply.github.com>
Co-authored-by: Jeremy Whitlock <jcwhitlock@google.com>
Co-authored-by: Laurent Broudoux <laurent.broudoux@gmail.com>
Co-authored-by: Lukasz Gornicki <lpgornicki@gmail.com>
```

**Comment by vearutop** [comment]
Why were all the JSON schemas deleted in this PR?

**Comment by jonaslagoni** [comment]
@vearutop they were moved here: https://github.com/asyncapi/spec-json-schemas/tree/master/bindings

**Pull request merged**
