### PR TITLE
docs: align requirement wording with RFC 2119

### PR DESCRIPTION
**Pull request by char0n**
Refs https://github.com/swagger-api/apidom/issues/1663

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]

**Comment by char0n** [comment]
@GeraldLoeffler @derberg can I ask you to look into this PR? Thanks!

**Review by derberg — APPROVED** [review]

**Review by GeraldLoeffler — APPROVED** [review]
fully agreed: thanks for cleaning this up!

**Comment by char0n** [comment]
@derberg please allow the workflow to run after merge from `master`.

**Comment by derberg** [comment]
@char0n done

**Comment by char0n** [comment]
This looks like good to go.

**Pull request merged**
